import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import Footer from "./Footer";
import Navbar from "./Navbar";
import "./globals.css";

const ununtu = Ubuntu({
  subsets: ["greek"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ununtu.className}>
        <Navbar />
        {children}
      </body>
      <Footer />
    </html>
  );
}
